version: "2.3"
services:
  db:
    image: postgres:12.1
    restart: always
    shm_size: '512m'
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: altcen
      POSTGRES_PASSWORD: local

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - ./:/app
    environment:
      FLASK_APP: alt2
      FLASK_DEBUG: development
      ALTC_DATABASE_URL: "${ALTC_DATABASE_URL}"
      ALTC_SECRET_KEY: "${ALTC_SECRET_KEY}"
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=80